language: c++
dist: bionic
compiler:
  - gcc
  - clang

before_install:
 - git clone https://github.com/xanthospap/ggdatetime.git && cd ggdatetime
 - mv src/Makefile.am.production src/Makefile.am
 - autoreconf -if
 - ./configure
 - make
 - sudo make install

script:
 - mv src/Makefile.am.production src/Makefile.am
 - autoreconf -if
 - ./configure
 - make
